### PR TITLE
Rewrite annotater in rust

### PR DESCRIPTION
**Pull request by breezykermo**
The Python script that reads the bitmap masks produced by Unreal/Unity has always been quite slow. This is more due to the implementation (it inefficiently loops over the pixels in the image multiple times) than the language, but I thought it would be a good opportunity to write something small and self-contained in Rust.

The script "works" currently, but I need to test that its annotations are accurate by uploading them to Supervisely. I will also write a small test suite with example inputs/outputs, to programmatically confirm masks are being correctly inferred.

Having these scripts be robust is important, not least because I'll be updating these scripts in a range of ways over the next few months. Here are a few of the ways:
- to parallelize inference across multiple masks (another good reason this is better in Rust).
- to support inferring annotations with _multiple labels_, rather than just one.
- integrating Pascal Vox dataset creation directly from the game engine masks, which is much more efficient than having the separate scripts to run afterwards. I've architected the scripts in such a way that it should be straightforward to add new annotation types as modules, which can be 'rendered' directly from the intermediate representation of masks that 'anns.rs' works out.

### CODE REVIEW

**Comment by breezykermo** [comment]
@frnsys any pointers would be appreciated! This is the first thing I've properly done in Rust, there's definitely a heap that isn't idiomatic/efficient.

**Comment by frnsys** [comment]
> @frnsys any pointers would be appreciated! This is the first thing I've properly done in Rust, there's definitely a heap that isn't idiomatic/efficient.

taking a look now!

**Comment by frnsys** [comment]
It looks good to me--I made a few changes, nothing major:

- Use an enum for the custom errors. I find it easier to work with, especially for extending with different error types if you end up needing more fine-grained error handling. Also implemented `From<&str>` for it to make creating them from `&str` a bit easier.
- There were a few `String.clone()`s happening where it was fine to just borrow the string
- When you use `println!(...)` you can just `{:?}` instead of `{}`, which will use the type's implementation of `Display` if it has one (so you don't need to manually convert it to a string)

I can't push to this repo but the changes are here: https://github.com/frnsys/scripts/tree/topic/rust_rewrite

**Comment by breezykermo** [comment]
Beautiful thanks a heap @frnsys! Will be furthering tomorrow, very much appreciated

**Comment by breezykermo** [comment]
There's something particular about how Supervisely expects bitmap annotations. I haven't been able to replicate the transformation yet to get the Supervisely uploaded to accept the string ([see here](https://docs.supervise.ly/data-organization/00_ann_format_navi/04_supervisely_format_objects#bitmap) for more info). 

I'm going to leave this as is for the time being, as it works minimally (for generating annotated datasets with bounding boxes), and push fixes in later PRs.

**Pull request merged**
